# Generated by Django 4.2.7 on 2023-12-10 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_userinfo_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("男", "男"),
                    ("女", "女"),
                    ("不便透露", "不便透露"),
                    ("跨性别认知者", "跨性别认知者"),
                ],
                default="不便透露",
                max_length=20,
                null=True,
            ),
        ),
    ]
