# Generated by Django 4.2.7 on 2023-12-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_alter_userinfo_age_alter_userinfo_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="avatar",
            field=models.ImageField(
                default="D:/ml_Py/djangoProject/django_py/py_django/app01/static/img/1.png",
                upload_to="avatars/",
            ),
        ),
    ]
