# Generated by Django 4.2.7 on 2023-12-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0005_alter_userinfo_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="avatar",
            field=models.ImageField(default="/media/11.png", upload_to="avatars/"),
        ),
    ]
